### PR TITLE
Remove unused declaration of get1char

### PR DESCRIPTION
**Pull request by gahr**

### CODE REVIEW

**Comment by nsd20463** [comment]
I'd want to keep that one around just so that if, in the future, due to
some modification, I end up passing in a std::string, that I don't have to
being it back. Being "static inline" it gets compiled out without a warning
if nothing uses it.

Was it causing you trouble?

-N

**Comment by gahr** [comment]
No trouble, just a warning:

pwsafe.cpp:428:20: warning: unused function 'get1char' [-Wunused-function]

This is with clang 3.4.1

**Comment by nsd20463** [comment]
> clang

...apt-get install clang (3.5.0 since that's the default on this distro)...
ah 4 warnings. The other 3 I should fix. This one I think I'll just comment
out the function.

thanks.

-N

**Comment by nsd20463** [comment]
thanks again for the patch, and for making me try clang (something I'd never investigated)

**Comment by gahr** [comment]
Clean with clang 3.6.1 and gcc 6.0.0 20150524  as well! Thanks!

**Pull request merged**
